import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Toaster } from "@/components/ui/sonner";
import CoordinateurHeader from "@/components/reusable/coordinateurHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Coordinateur Interface",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-screen">
              <SidebarTrigger className="fixed z-[50] hover:cursor-pointer"/>
              <CoordinateurHeader />
              {children}
              <Toaster/>
            </main>
          </SidebarProvider>
      </div>
  );
}
